Repository LikeLionMini2/BE, pull requests merged in 2025-05, with the labels that each got.

#30 Feat : 로그인 API 추가
  src/main/java/com/manittotie/manilib/auth/controller/AuthController.java
  src/main/java/com/manittotie/manilib/auth/service/AuthService.java
  src/main/java/com/manittotie/manilib/config/SecurityConfig.java
  src/main/java/com/manittotie/manilib/member/service/MemberService.java
Labels: ✨ Feature

#32 Feat : 이메일 중복 확인 API 생성
  src/main/java/com/manittotie/manilib/member/controller/MemberController.java
  src/main/java/com/manittotie/manilib/member/dto/DuplicateEmailRequest.java
  src/main/java/com/manittotie/manilib/member/dto/DuplicateEmailResponse.java
  src/main/java/com/manittotie/manilib/member/service/MemberService.java
Labels: ✨ Feature

#45 Feat : 특정 그룹 가입 API 생성 & Fix : 관리자 인식 오류 수정
  src/main/java/com/manittotie/manilib/auth/jwt/JwtFilter.java
  src/main/java/com/manittotie/manilib/groups/controller/GroupController.java
  src/main/java/com/manittotie/manilib/groups/repository/GroupRepository.java
  src/main/java/com/manittotie/manilib/groups/repository/MemberGroupRepository.java
  src/main/java/com/manittotie/manilib/groups/service/GroupService.java
Labels: ✨ Feature, 🐞 BugFix

#46 Feat: Add Group
  src/main/java/com/manittotie/manilib/groups/controller/GroupController.java
  src/main/java/com/manittotie/manilib/groups/dto/AllGroupResponse.java
  src/main/java/com/manittotie/manilib/groups/dto/MyGroupResponse.java
  src/main/java/com/manittotie/manilib/groups/repository/GroupRepository.java
  src/main/java/com/manittotie/manilib/groups/repository/MemberGroupRepository.java
  src/main/java/com/manittotie/manilib/groups/service/GroupService.java
Labels: 🐞 BugFix

#48 Feature/group fix
  src/main/java/com/manittotie/manilib/groups/controller/GroupController.java
  src/main/java/com/manittotie/manilib/groups/dto/AllGroupResponse.java
  src/main/java/com/manittotie/manilib/groups/dto/MyGroupResponse.java
  src/main/java/com/manittotie/manilib/groups/repository/GroupRepository.java
  src/main/java/com/manittotie/manilib/groups/repository/MemberGroupRepository.java
  src/main/java/com/manittotie/manilib/groups/service/GroupService.java
  src/main/java/com/manittotie/manilib/matching/domain/MatchingResult.java
  src/main/java/com/manittotie/manilib/matching/domain/MatchingSession.java
  src/main/java/com/manittotie/manilib/matching/listener/MatchingSessionListener.java
Labels: 🐞 BugFix

#49 Feat : 마니또 매칭 API 생성
  src/main/java/com/manittotie/manilib/auth/dto/CustomUserDetails.java
  src/main/java/com/manittotie/manilib/groups/repository/MemberGroupRepository.java
  src/main/java/com/manittotie/manilib/matching/controller/MatchingController.java
  src/main/java/com/manittotie/manilib/matching/dto/MatchingResultDto.java
  src/main/java/com/manittotie/manilib/matching/repository/MatchingResultRepository.java
  src/main/java/com/manittotie/manilib/matching/repository/MatchingSessionRepository.java
  src/main/java/com/manittotie/manilib/matching/service/MatchingService.java
Labels: ✨ Feature

#51 Feature/matching
  src/main/java/com/manittotie/manilib/matching/controller/MatchingController.java
  src/main/java/com/manittotie/manilib/matching/domain/MatchingSession.java
  src/main/java/com/manittotie/manilib/matching/repository/MatchingResultRepository.java
  src/main/java/com/manittotie/manilib/matching/repository/MatchingSessionRepository.java
  src/main/java/com/manittotie/manilib/matching/service/MatchingService.java
Labels: ✨ Feature

#52 Feat : 그룹 삭제 API 생성
  src/main/java/com/manittotie/manilib/groups/controller/GroupController.java
  src/main/java/com/manittotie/manilib/groups/dto/MessageResponse.java
  src/main/java/com/manittotie/manilib/groups/service/GroupService.java
Labels: ✨ Feature

#53 Feature/comment
  src/main/java/com/manittotie/manilib/manitottipost/controller/CommentController.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/AddCommentRequest.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/AddCommentResponse.java
  src/main/java/com/manittotie/manilib/manitottipost/repository/CommentRepository.java
  src/main/java/com/manittotie/manilib/manitottipost/service/CommentService.java
Labels: ✨ Feature

#56 Feat: Add Update Comment
  global-commit.txt
  src/main/java/com/manittotie/manilib/groups/repository/GroupRepository.java
  src/main/java/com/manittotie/manilib/manitottipost/controller/CommentController.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/UpdateCommentRequest.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/UpdateCommentResponse.java
  src/main/java/com/manittotie/manilib/manitottipost/service/CommentService.java
Labels: ✨ Feature

#63 Feat : 그룹 내 전체 게시글 조회 API 생성
  src/main/java/com/manittotie/manilib/groups/repository/MemberGroupRepository.java
  src/main/java/com/manittotie/manilib/manitottipost/controller/ManiPostController.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/GetManiPostResponse.java
  src/main/java/com/manittotie/manilib/manitottipost/service/ManiPostService.java
Labels: ✨ Feature

#64 Refactor: Update Comment 코드 수정
  src/main/java/com/manittotie/manilib/manitottipost/dto/AddCommentResponse.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/UpdateCommentResponse.java
  src/main/java/com/manittotie/manilib/manitottipost/service/CommentService.java
Labels: 🔨 Refactor

#66 Feat: 마이페이지 조회 API 생성
  src/main/java/com/manittotie/manilib/mypage/controller/MyPageController.java
  src/main/java/com/manittotie/manilib/mypage/dto/MyPageGroupResponse.java
  src/main/java/com/manittotie/manilib/mypage/dto/MyPageResponse.java
  src/main/java/com/manittotie/manilib/mypage/service/MyPageService.java
Labels: ✨ Feature

#69 Feature/get member profile
  src/main/java/com/manittotie/manilib/guestbook/domain/GuestBook.java
  src/main/java/com/manittotie/manilib/member/domain/Member.java
  src/main/java/com/manittotie/manilib/member/repository/MemberRepository.java
  src/main/java/com/manittotie/manilib/mypage/dto/MyPageGroupResponse.java
  src/main/java/com/manittotie/manilib/mypage/dto/MyPageResponse.java
  src/main/java/com/manittotie/manilib/mypage/service/MyPageService.java
Labels: ✨ Feature

#72 Fix : 매칭 API, 매칭 공개 API, 전체 멤버 조회 API 수정
  deploy.sh
  manitotti-test-ver1.pem
  src/main/java/com/manittotie/manilib/guestbook/domain/GuestBook.java
  src/main/java/com/manittotie/manilib/guestbook/dto/AddGuestBookRequest.java
  src/main/java/com/manittotie/manilib/guestbook/dto/GuestBookResponse.java
  src/main/java/com/manittotie/manilib/guestbook/repository/GuestBookRepository.java
  src/main/java/com/manittotie/manilib/guestbook/service/GuestBookService.java
  src/main/java/com/manittotie/manilib/matching/controller/MatchingController.java
  src/main/java/com/manittotie/manilib/matching/domain/MatchingSession.java
  src/main/java/com/manittotie/manilib/matching/dto/MatchingStatusResponse.java
  src/main/java/com/manittotie/manilib/matching/repository/MatchingResultRepository.java
  src/main/java/com/manittotie/manilib/matching/repository/MatchingSessionRepository.java
  src/main/java/com/manittotie/manilib/matching/service/MatchingService.java
  src/main/java/com/manittotie/manilib/member/controller/MemberController.java
  src/main/java/com/manittotie/manilib/member/dto/GroupMemberWithMatchResponse.java
  src/main/java/com/manittotie/manilib/member/service/MemberService.java
Labels: 🔨 Refactor, 🐞 BugFix

#74 Feat : 방명록 작성 API 생성
  src/main/java/com/manittotie/manilib/guestbook/controller/GuestBookController.java
Labels: ✨ Feature

#75 Fix: Delete Comment by Admin
  src/main/java/com/manittotie/manilib/manitottipost/controller/CommentController.java
  src/main/java/com/manittotie/manilib/manitottipost/service/CommentService.java
Labels: 🐞 BugFix

#78 Feat: 게시판 수정 API 추가
  src/main/java/com/manittotie/manilib/manitottipost/controller/ManiPostController.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/UpdateManiPostRequest.java
  src/main/java/com/manittotie/manilib/manitottipost/dto/UpdateManiPostResponse.java
  src/main/java/com/manittotie/manilib/manitottipost/service/ManiPostService.java
Labels: ✨ Feature

#80 Fix : 방명록 API 전체 수정
  src/main/java/com/manittotie/manilib/guestbook/controller/GuestBookController.java
  src/main/java/com/manittotie/manilib/guestbook/domain/GuestBook.java
  src/main/java/com/manittotie/manilib/guestbook/repository/GuestBookRepository.java
  src/main/java/com/manittotie/manilib/guestbook/service/GuestBookService.java
  src/main/java/com/manittotie/manilib/member/domain/Member.java
Labels: 🐞 BugFix

#81 Feat: 프로필 조회 API 추가
  src/main/java/com/manittotie/manilib/member/controller/MemberController.java
  src/main/java/com/manittotie/manilib/member/dto/ProfileResponse.java
  src/main/java/com/manittotie/manilib/member/service/MemberService.java
Labels: ✨ Feature
